### ISSUE TITLE
Plugin interprets text separated by underscores as different words.

### ISSUE THREAD

**Issue by unblevable** [unblevable/quick-scope#10]
![image](https://cloud.githubusercontent.com/assets/723755/9238453/2ff26a76-4107-11e5-8c7b-d35d1c2f5a51.png)

**Comment by cszentkiralyi** [comment]
This is also true with dashes in cases where a word is allowed to contain them, e.g. Clojure:

![dashes treated as separate words](https://cloud.githubusercontent.com/assets/12720943/9252839/c2390d6e-4197-11e5-82a1-adefac6fd076.PNG)
