### ISSUE TITLE
ignore case option

### ISSUE THREAD

**Issue by hallzy** [unblevable/quick-scope#15]
I think it would be useful to have an option to disable case sensitivity (ie, it highlights the first m or M but not both).

Reason being, is I use fanfingtastic, which gives some nice features and also gives the option to use the f F t and T commands without case sensitivity, so if I do fw to get to the next w in a line with this plugin, it may take me to the next capital W which is before the next w

ex:

This i[s] just a Test

where [] shows where my cursor is, if I do fT it will take me to this point:

This is jus[t] a Test

Which can be confusing when the letter that the cursor moves to is not highlighted.

**Comment by CallumHoward** [comment]
I came here to suggest this feature also, I think this would be great!

**Comment by stfl** [comment]
+1

**Comment by ratheesh** [comment]
It will be nice to implement smartcase along with ignorecase option.

**Comment by dseeni** [comment]
haha I cam here for this option too, ignore case toggle would be nice so I can get precise results with other plugins

**Comment by bradford-smith94** [comment]
You can now set `g:qs_ignorecase = 1` to achieve this!
