### ISSUE TITLE
sourcing after startup ruins highlighting

### ISSUE THREAD

**Issue by nhooyr** [unblevable/quick-scope#17]
sourcing my .nvimrc file again after starting up seems to screw up the highlighting, it just doesn't want to highlight anymore. I have this defined for the plugin: 

```
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
let g:qs_second_occurrence_highlight_color = 1
let g:qs_first_occurrence_highlight_color = 2
```

my vim resource mapping

```
nmap <leader>rr :source ~/.nvimrc<CR>
```

**Comment by jonohrt** [comment]
I'm still seeing this same issue in terminal Neovim when sourcing my init.vim file. Highlighting works fine on startup until I source init.vim, then highlighting stops working until I restart Neovim.
