### ISSUE TITLE
No longer works together with solarized color scheme

### ISSUE THREAD

**Issue by patrickdepinguin** [unblevable/quick-scope#19]
quick-scope used to work for me. Then I upgraded my distribution (from Linux Mint Debian edition to Debian) and quick-scope no longer works, _unless_ I disable the 'solarized' colorscheme. 

So, commenting out following lines from my vimrc file 'fixes' the issue:

```
let g:solarized_termcolors=256
colorscheme solarized
```

The colorscheme is added using Vundle with following line:

```
Plugin 'altercation/vim-colors-solarized'
```

I'm using commit 483e3b62cad7d341e3249987a96c42e6235b1449 for quick-scope (latest as of this writing) and solarized commit 528a59f26d12278698bb946f8fb82a63711eec21 (also latest). 

Any idea on how to proceed investigating this?

**Comment by unblevable** [comment]
I can't seem to reproduce the error. Can you try the latest pull request (#20) or show my your `.vimrc`?

**Comment by patrickdepinguin** [comment]
Pull request #20 fixes this issue indeed, thanks.
