### ISSUE TITLE
Requires vim >= 7.1.040

### ISSUE THREAD

**Issue by patrickdepinguin** [unblevable/quick-scope#22]
quick-scope uses getmatches which is only added in vim 7.1.040. If you load it with an older vim version, you get continuous errors when moving and it is not workable.

A similar problem is reported in another plugin too:
https://github.com/scrooloose/syntastic/issues/250

Loading the plugin conditionally on the following check avoids these problems:

```
if v:version > 701 || (v:version == 701 && has('patch040'))
    Plugin 'unblevable/quick-scope'
endif
```

But I think this check should be inside the plugin itself.

**Comment by unblevable** [comment]
Thanks for the find!
