### ISSUE TITLE
[propose] disable plugin when line is too long?

### ISSUE THREAD

**Issue by liujoey** [unblevable/quick-scope#23]
Some times when I editing a file (sql for instance or minified javascript) there might be very long lines in the file, can we have an option that if a line has more than certain number of characters then the plugin should disable it self on that line?

**Comment by sunaku** [comment]
:+1:

**Comment by patrickdepinguin** [comment]
On lines that are very long for example 800000+ characters, vim just hangs when quick-scope is enabled. An example is an html file with a javascript framework included, see file https://github.com/gnab/remark/blob/develop/boilerplate-single.html line 41.

Disabling quick-scope entirely makes scrolling across the line very quick again.
With quick-scope enabled and the proposed patch (pull request #29) applied, vim does not hang but the editing is not as swift as with quick-scope disabled, even when changing the max-chars to 100 or even 10.
I proposed another solution in pull request #31.

**Comment by iryan2** [comment]
Yeah this is a problem for me too. One line css sourcemaps causes neovim to hang if the cursor moves to that line.

Would love to be able to disable quickscope for gitcommit filetype only.
