### ISSUE TITLE
Highlighting goes away when doing split operations

### ISSUE THREAD

**Issue by nkakouros** [unblevable/quick-scope#47]
This is really minor.

Open a file and two splits. Make sure quick-scope highlighting appears. 

Now type `<c-w>s`. A new split is created. The quick scope highlighting is now gone. You have to move the cursor to get it show again.

Another thing. Open the same file in two splits and move on both splits on the same line. Now type `<c-w><c-w>` to move between the two splits. The go-to split turns off the quick-scope highlighting.

**Comment by bradford-smith94** [comment]
An easy fix too.

It took me longer than I intended to get to this, sorry about that.
