### ISSUE TITLE
disable quickscope highlighting for floating window

### ISSUE THREAD

**Issue by alexlai97** [unblevable/quick-scope#50]
![screenshot-2019-09-27@22 22 35](https://user-images.githubusercontent.com/17771269/65810202-714ff700-e175-11e9-8cf9-be4119e9467c.png)

I am using coc.nvim with neovim 0.4.2. The floating window in the picture has quickscope lightlight enabled for the first line. Even I did `:QuickscopeToggle`, the highlight is still there. I am not sure where the problem is.

**Comment by Avi-D-coder** [comment]
Do you have `let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']` in your vimrc?

**Comment by alexlai97** [comment]
> Do you have `let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']` in your vimrc?

Yes.

**Comment by webdavis** [comment]
Create a file called `cocactions.vim` in the `ftplugin` directory, so `~/.vim/ftplugin/cocactions.vim` and put the following in it:

```vim
let b:qs_local_disable = 1
```
Works for me using Neovim (`nvim --version`):

```
NVIM v0.5.0-397-g96059d72e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by webdavis** [comment]
Not sure about how to solve for regular floating windows, as they don't have a filetype. They are the buffer type `nofile`. That might be a way to solve.

**Comment by webdavis** [comment]
@alexlai97 add the following to your vimrc if you're using coc.nvim:

```vim
" This works for the floating window created by the `coc-actions` extension, as well.
let g:qs_buftype_blacklist = ['nofile']
```
