### ISSUE TITLE
do not highlight secondary

### ISSUE THREAD

**Issue by ahmadie** [unblevable/quick-scope#53]
I use , and ; for other tasks in vim

How can i disable secondary highlight ?
I tried
highlight QuickScopeSecondary guifg=NONE gui=NONE ctermfg=NONE cterm=NONE
but default color is applied...

**Comment by bradford-smith94** [comment]
You can now use `let g:qs_second_hightlight=0`.

**Comment by nkcfan** [comment]
I notice a typo `g:qs_second_highlight`
Also in document
