### ISSUE TITLE
cannot use f and t in macro

### ISSUE THREAD

**Issue by againxx** [unblevable/quick-scope#56]
This plugin seems to break f and t in macro, when I recorded f in macro and replayed it, the cursor didn't goto the expected position.

I observed the same issue in vim-sneak (label mode), but it's ok in normal vim-sneak mode.

Any suggestions? Thank you!

**Comment by bradford-smith94** [comment]
Could you provide a minimal working example of the issue you're seeing? I haven't noticed any problems using f/F/t/T in macros.

**Comment by againxx** [comment]
I'm sorry, after investigation, I found that the problem comes from the modification proposed by https://github.com/unblevable/quick-scope/issues/55#issuecomment-629721429. After I removed this patch, f and t now work fine in macro. Maybe I should make the further check why resetting of sneak breaks the macro.
