### ISSUE TITLE
quick-scope taking 100% of CPU

### ISSUE THREAD

**Issue by isakhammer** [unblevable/quick-scope#68]
For some reason does quick-scope take 100% of my CPU when I am editing in latex and slows vim down alot. Any idea why?

![pic-full-201203-1008-05](https://user-images.githubusercontent.com/43385748/100988144-ad3bd480-354f-11eb-8af6-61fa437643d0.png)

Here is my vimrc:

```
if ! filereadable(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/vim/autoload/plug.vim"'))
        echo "Downloading junegunn/vim-plug to manage plugins..."
        silent !mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/vim/autoload/
        silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ${XDG_CONFIG_HOME:-$HOME/.config}
/vim/autoload/plug.vim
        autocmd VimEnter * PlugInstall
endif

call plug#begin(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/vim/plugged"'))
Plug 'unblevable/quick-scope'
call plug#end()

```

**Comment by bradford-smith94** [comment]
I don't have any initial ideas, but the latest version (literally just pushed) includes #64. Can you try with the latest version to see if the timer delay fixes this?

**Comment by isakhammer** [comment]
Nevermind. Changed operating system and it worked normal again. No idea why.
