### ISSUE TITLE
underline target characters without changing its color

### ISSUE THREAD

**Issue by smartding** [unblevable/quick-scope#70]
I just want to underline the target characters while keeping the rest of its original highlight setting.
Is this possible?

**Comment by bradford-smith94** [comment]
Just removing the colors from the highlight group should work, try something like the following:

```
augroup qs_colors
  autocmd!
  autocmd ColorScheme * highlight QuickScopePrimary gui=underline cterm=underline
  autocmd ColorScheme * highlight QuickScopeSecondary gui=underline cterm=underline
augroup END
```

**Comment by smartding** [comment]
> Just removing the colors from the highlight group should work, try something like the following:
> 
> ```
> augroup qs_colors
>   autocmd!
>   autocmd ColorScheme * highlight QuickScopePrimary gui=underline cterm=underline
>   autocmd ColorScheme * highlight QuickScopeSecondary gui=underline cterm=underline
> augroup END
> ```
thanks.
It works with regex based syntax highlighting.
But it doesn't with treesitter highlighting. The underline works, but some of the target characters shows a different color.
I'm using neovim with latest master, lua treesitter parser.

**Comment by smartding** [comment]
It's all working now
