### ISSUE TITLE
highlight not working with vimtex

### ISSUE THREAD

**Issue by ferdinandyb** [unblevable/quick-scope#83]
The highlighting doesn't turn on in my tex files (I'm using vimtex), although f still works. I tried setting the highlighting priority, but that didn't help. Any ideas on how I could troubleshoot what's going on?

**Comment by bradford-smith94** [comment]
I'm not exactly sure. `:scriptnames` can print you a list of the ordrer in which startup files are sourced. `:highlight` without other arguments will give a list of all highlight groups and their current values, so you can check for QuickScopePrimary and QuickScopeSecondary in that list to see what values they get.

**Comment by ferdinandyb** [comment]
I have no idea what has happened, but it works now, so I'm closing the issue.
