### ISSUE TITLE
check-spell on quick-scope highlighted letters

### ISSUE THREAD

**Issue by echaya** [unblevable/quick-scope#89]
Hi, 

[This might not be a issue from quick-scope but rather on nvim setting, but I can't find anything via goolging]

I have recently updated my nvim to 0.8.1 (from 0.7) and can't stop noticing that all the quick-scope highlighted letters show red underlines. May I please check if anyone knows how to turn it off? Many thanks in advance!

![image](https://user-images.githubusercontent.com/34254408/206350711-e398e91e-36eb-4189-90cc-be55a7476529.png)

**Comment by bradford-smith94** [comment]
Can you show the output of: `:verbose hi QuickScopePrimary` and `:verbose hi QuickScopeSecondary` they should show us when the quick-scope highlight groups were last set and what their values are. I expect they will match the screenshot you already included, but if they're updated from a weird place that could give us a hint.

In either case you can follow the "customize colors" section of the README (https://github.com/unblevable/quick-scope#customize-colors) to change them, maybe removing the underline from the highlights will resolve your issue? (Unless you would like to keep the underline - just in the correct color)

**Comment by echaya** [comment]
> Can you show the output of: `:verbose hi QuickScopePrimary` and `:verbose hi QuickScopeSecondary` they should show us when the quick-scope highlight groups were last set and what their values are. I expect they will match the screenshot you already included, but if they're updated from a weird place that could give us a hint.
> 
> In either case you can follow the "customize colors" section of the README (https://github.com/unblevable/quick-scope#customize-colors) to change them, maybe removing the underline from the highlights will resolve your issue? (Unless you would like to keep the underline - just in the correct color)

Thanks much! - i overlooked a setting in my .vimrc. But apparently the new NVIM has changed some of the display logics.

**Comment by echaya** [comment]
Actually following is my settings in my `.vimrc` but still it gives me red underlines instead of intended green or blue per my screenshot above. 

```vim
    let g:qs_lazy_highlight = 0
    highlight QuickScopePrimary guifg=#afff5f gui=underline ctermfg=155 cterm=underline
    highlight QuickScopeSecondary guifg=#5fffff gui=underline ctermfg=81 cterm=underline

```

**Comment by echaya** [comment]
Fwiw, https://github.com/equalsraf/neovim-qt/issues/929#issuecomment-1264398085 has the exact same problem & solution.
Configuration details can be found on https://github-wiki-see.page/m/equalsraf/neovim-qt/wiki/Configuration-Options
