### ISSUE TITLE
error after migration to lazy-nvim

### ISSUE THREAD

**Issue by fdelacruz** [unblevable/quick-scope#91]
I'm getting this error, but only after migrating to lazy-nvim
```
Error detected while processing function quick_scope#HighlightLineDelayCallback[2]..quick_scope#HighlightLine[12]..<SNR>83_get_highlight_patterns[130]..<SNR>83_save_chars_with_secondary_highlights:
line    6:
E121: Undefined variable: s:chars_s
Press ENTER or type command to continue
```

**Comment by fdelacruz** [comment]
Also settings like
`vim.g.qs_highlight_on_keys = { "f", "F", "t", "T" }`
stopped working

**Comment by fdelacruz** [comment]
I needed to add lazy = false to the QS configuration

**Comment by guidiamond** [comment]
What solved this for me was to use `init` rather than `config` to set the `quickscope` settings.

It seems like in order for this plugin to work properly, the global variables need to be set first.
