### ISSUE TITLE
Underline with default plugin color

### ISSUE THREAD

**Issue by mklimkin0190** [unblevable/quick-scope#99]
I like the default color settings, but I'd like to add an underline to them.
Customizing the colors as directed in the docs adds an underline but it changes the colors to the given ones as well.
Or, if I leave the color out in the custom settings, it only underlines the characters, keeping the default color scheme colors.
I'd like to keep the default color settings of this plugin but add the underline, and I didn't find how it can be done easily without redefining the color variables on plugin load (and eve that didn't go well for me).

**Comment by bradford-smith94** [comment]
The default colors are actually links to other highlight groups, so they depend on your colorscheme. The details should also be in the help page `:h qs-customize-colors`, but the primary highlight links to "Function" and the secondary highlight links to "Define".

To see what those colors are in your case you can use `:hi Function` and `:hi Define`.

**Comment by mklimkin0190** [comment]
Thanks! This is not what I was expecting but it works :)
